[workspace]
members = [".", "kraken-protocol"]
resolver = "2"

[package]
name = "kraken"
version = "0.1.0"
edition = "2021"
description = "High-performance Minecraft server"

[dependencies]
mimalloc = "0.1"
noise = "0.9"
tokio = { version = "1.36", features = ["full"] }
owo-colors = { version = "4", features = ["supports-colors"] }
chrono = "0.4.44"
sled = "0.34.7"
bytes = "1.11.1"
postcard = { version = "1.1.3", features = ["alloc"] }
flate2 = "1.1.9"
serde = { version = "1.0.228", features = ["derive"] }
ctrlc = "3.5.2"
azalea-world = "0.16.0"
bevy_app = "0.18.1"
bevy_ecs = "0.18.1"
sysinfo = "0.33"
rustc_version_runtime = "0.3"
uuid = { version = "1.23.1", features = ["v4", "serde"] }
kraken_protocol = { path = "kraken-protocol", features = ["tokio-defaults", "v1_21_11", "v26_1"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_System_Console", "Win32_Foundation"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true # Further reduces binary size by removing debug symbols
